### PR TITLE
feat: add origin to email args

### PR DESCRIPTION
**Pull request by codingnuclei**

### CODE REVIEW

**Review by fribas84 — APPROVED** [review]
G2M

**Review by bhavyagor12 — COMMENTED** [review]
should we push yarn.lock?

**Comment by codingnuclei** [comment]
> should we push yarn.lock?

Yea lock files should be pushed in general.

I think here it is being added because my last PR i had not updated it properly before pushing :(

**Comment by fribas84** [comment]
Two cents: lock files help to fix the dependencies versions, package.json
most cases have ˆ, meaning any version greater than. With the lock, we set
a common base and run the same code.

**Pull request merged**
